# train_model.py

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# pip install tensorflow scikit-learn seaborn joblib
from positioning_model import UWBPositioningNN

# --- Configuration ---
UWB_FILE = 'k501_t1.csv'       # From your Windows App
LIDAR_FILE = 'lidar_ground_truth_20260121_153856.csv' # From your Robot
MODEL_SAVE_PATH = 'models/nn_model'

def merge_datasets():
    print("--- 1. Synchronizing Data Files ---")
    try:
        # 1. Load the files
        df_uwb = pd.read_csv('uwb_training_data.csv')
        df_lidar = pd.read_csv('cleaned_lidar_data.csv')
        
        # 2. Process UWB Timestamps
        # Verify if UWB data has time information
        if 'Timestamp' in df_uwb.columns:
            df_uwb['Timestamp'] = pd.to_datetime(df_uwb['Timestamp'])
            
            # CHECK: If all times are midnight (00:00:00), the data is broken (Excel issue)
            if df_uwb['Timestamp'].dt.time.nunique() == 1:
                print("CRITICAL WARNING: Your UWB file only has Dates (e.g., 1/20/2026) but NO TIME.")
                print("This usually happens if you opened the CSV in Excel and clicked Save.")
                print("You must use the original file generated by the Python App.")
                return None
        
        # 3. Process Lidar Timestamps (The Fix for your Error)
        # We look for the 'timestamp(seconds)' column which has the raw numbers
        if 'timestamp(seconds)' in df_lidar.columns:
            df_lidar['timestamp_dt'] = pd.to_datetime(df_lidar['timestamp(seconds)'], unit='s')
        elif 'timestamp' in df_lidar.columns:
            # Fallback: Try reading the string, but do NOT force unit='s'
            df_lidar['timestamp_dt'] = pd.to_datetime(df_lidar['timestamp'])
        else:
            print("Error: Could not find any timestamp column in Lidar file.")
            return None

        # 4. Sort and Merge
        df_uwb = df_uwb.sort_values('Timestamp')
        df_lidar = df_lidar.sort_values('timestamp_dt')

        # Merge based on nearest time (Allow up to 1 second difference)
        merged_df = pd.merge_asof(
            df_uwb, 
            df_lidar, 
            left_on='Timestamp', 
            right_on='timestamp_dt', 
            direction='nearest',
            tolerance=pd.Timedelta('1s')
        )
        
        # 5. Clean up
        merged_df.dropna(subset=['x', 'y', 'Dist_A'], inplace=True)
        print(f"Successfully matched {len(merged_df)} synchronized data points.")
        
        return merged_df

    except Exception as e:
        print(f"Error merging data: {e}")
        return None
    
def evaluate_and_visualize(model: UWBPositioningNN, X: np.ndarray, y: np.ndarray, history):
    """
    Evaluates the trained model and creates detailed plots to visualize its performance.
    """
    print("\n--- Evaluating Final Model Performance ---")

    # 1. Make predictions on the entire dataset
    X_scaled = model.scaler.transform(X)
    y_pred = model.model.predict(X_scaled)

    # 2. Calculate errors in centimeters
    errors_m = np.sqrt(np.sum((y - y_pred) ** 2, axis=1))
    errors_cm = errors_m * 100

    # 3. Print key performance metrics
    rmse_cm = np.sqrt(np.mean(errors_m**2)) * 100
    mae_cm = np.mean(errors_cm)
    p95_cm = np.percentile(errors_cm, 95)

    print("\n--- FINAL METRICS (on full dataset) ---")
    print(f"Root Mean Square Error (RMSE): {rmse_cm:.2f} cm  <-- YOUR GOAL METRIC")
    print(f"Mean Absolute Error (MAE):    {mae_cm:.2f} cm")
    print(f"95th Percentile Error (P95):  {p95_cm:.2f} cm (95% of errors are below this value)")
    print("-----------------------------------------")

    # 4. Create comprehensive visualizations
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, axes = plt.subplots(2, 2, figsize=(18, 14))
    fig.suptitle('Neural Network Model Performance Analysis', fontsize=20)

    # Plot 1: Training & Validation Loss
    ax = axes[0, 0]
    ax.plot(history.history['loss'], label='Training Loss')
    ax.plot(history.history['val_loss'], label='Validation Loss')
    ax.set_title('Model Training History (Loss)')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Mean Squared Error (Loss)')
    ax.legend()
    ax.grid(True)

    # Plot 2: Error Distribution (Histogram)
    ax = axes[0, 1]
    sns.histplot(errors_cm, bins=30, kde=True, ax=ax, color='skyblue')
    ax.axvline(mae_cm, color='r', linestyle='--', label=f'Mean Error: {mae_cm:.2f} cm')
    ax.axvline(p95_cm, color='purple', linestyle=':', label=f'P95 Error: {p95_cm:.2f} cm')
    ax.set_title('Distribution of Positioning Errors')
    ax.set_xlabel('Error (cm)')
    ax.set_ylabel('Frequency')
    ax.legend()
    ax.grid(True)

    # Plot 3: True vs. Predicted Coordinates
    ax = axes[1, 0]
    ax.scatter(y[:, 0], y_pred[:, 0], alpha=0.5, label='X coordinate')
    ax.scatter(y[:, 1], y_pred[:, 1], alpha=0.5, label='Y coordinate')
    lims = [min(ax.get_xlim()[0], ax.get_ylim()[0]), max(ax.get_xlim()[1], ax.get_ylim()[1])]
    ax.plot(lims, lims, 'k--', alpha=0.75, zorder=0, label='Perfect Prediction')
    ax.set_title('True vs. Predicted Positions')
    ax.set_xlabel('True Position (m)')
    ax.set_ylabel('Predicted Position (m)')
    ax.set_aspect('equal', adjustable='box')
    ax.legend()
    ax.grid(True)

    # Plot 4: Spatial Error Heatmap
    ax = axes[1, 1]
    df = pd.DataFrame({'true_x': y[:, 0], 'true_y': y[:, 1], 'error_cm': errors_cm})
    try:
        error_pivot = df.pivot_table(index='true_y', columns='true_x', values='error_cm')
        sns.heatmap(error_pivot, ax=ax, cmap='viridis', annot=True, fmt=".1f", cbar_kws={'label': 'Mean Error (cm)'})
        ax.set_title('Spatial Heatmap of Positioning Error')
        ax.invert_yaxis()
    except Exception as e:
        ax.set_title("Could not generate heatmap")
        ax.text(0.5, 0.5, f"Error: {e}", ha='center', va='center')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()
    
def main():
    # 1. Initialize your existing Neural Network
    model = UWBPositioningNN(anchor_ids=['A', 'B', 'C', 'D'])

    # 2. LOAD DATA (THE NEW WAY)
    df = merge_datasets()
    if df is None or len(df) < 50:
        print("Not enough data to train. Go collect more!")
        return

    # Extract features (Distances) and Targets (Lidar X/Y)
    # Note: Check your CSV headers to match these exact strings
    X = df[['Dist_A', 'Dist_B', 'Dist_C', 'Dist_D']].values
    y = df[['x', 'y']].values # These columns come from the Lidar CSV

    # 3. Train (Using your existing logic)
    # We pass the arrays directly to the model
    # Note: You might need to adjust 'train_model' in positioning_model.py 
    # if it strictly expects a filename string. 
    # Ideally, UWBPositioningNN should accept X/y arrays.
    
    print("--- 2. Training Model ---")
    history = model.train_model(X, y, epochs=200, batch_size=32)

    # 4. Save
    if model.is_trained:
        print(f"--- 3. Saving model to '{MODEL_SAVE_PATH}' ---")
        model.save(MODEL_SAVE_PATH)
        
        # Visualize (Your existing visualization code)
        evaluate_and_visualize(model, X, y, history)

if __name__ == "__main__":
    main()